    - name: Install and configure Apache
      block:
        - name: Install Apache
          yum:
            name: httpd
            state: present
            update_cache: yes

        - name: Enable Apache to start on boot
          systemd:
              name: httpd
              enabled: yes

        - name: Ensure Apache is running
          service:
              name: httpd
              state: started

      rescue:
          - debug:
              msg: "Failed to install or start Apache"

      always:
          - debug:
              msg: "Apache installation block finished"
      