    - name: Install and configure Apache
      block:
        - name: Install Apache
          apt:
            name: apache2
            state: present
            update_cache: yes

        - name: Enable Apache to start on boot
          systemd:
              name: apache2
              enabled: yes

        - name: Ensure Apache is running
          service:
              name: apache2
              state: started

      rescue:
          - debug:
            msg: "Failed to install or start Apache"

      always:
          - debug:
            msg: "Apache installation block finished"
      