    - name: Install and secure MySQL
      block:
        - name: Set MySQL root password 
          mysql_user:
            name: root
            host: localhost
            password: "{{ mysql_root_password }}"
            login_unix_socket: /var/lib/mysql/mysql.sock
            state: present
      rescue:
        - name: Rescue MySQL secure install failure
          debug:
            msg: "MySQL secure installation block failed"